apiVersion: apps/v1
kind: Deployment
metadata:
  name: librechat
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librechat
  template:
    metadata:
      labels:
        app: librechat
    spec:
      containers:
      - name: librechat
        image: ghcr.io/danny-avila/librechat-dev:latest
        ports:
        - containerPort: 3080
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "3080"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/LibreChat"
        - name: DOMAIN_CLIENT
          value: "https://librechat.cluster.dphx.eu"
        - name: DOMAIN_SERVER
          value: "https://librechat.cluster.dphx.eu"
        - name: JWT_SECRET
          value: "your-super-secret-jwt-key-change-this-in-production"
        - name: JWT_REFRESH_SECRET
          value: "your-super-secret-refresh-key-change-this-in-production"
        - name: CREDS_KEY
          value: "your-32-char-creds-key-change-this"
        - name: CREDS_IV
          value: "your-16-char-iv-key"
        - name: ALLOW_SOCIAL_LOGIN
          value: "true"
        - name: ALLOW_REGISTRATION
          value: "true"
        - name: ADMIN_EMAIL
          value: "benjamin.bachmayr@gmail.com"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
        - name: librechat-data
          mountPath: /app/client/public/images
        - name: config
          mountPath: /app/librechat.yaml
          subPath: librechat.yaml
      volumes:
      - name: librechat-data
        persistentVolumeClaim:
          claimName: librechat-pvc
      - name: config
        configMap:
          name: librechat-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
